In [3]:
import pandas as pd

In [12]:
original = '/Users/pawelkordowski/Desktop/desktop/prog_lang/sql/credit_cards/transactions_data.csv'
short = '/Users/pawelkordowski/Desktop/desktop/prog_lang/sql/credit_cards/transactions.csv'

rows = 10000

df_sample = pd.read_csv(original, nrows=rows)
df_sample.to_csv(short, index=False)

In [8]:
df = pd.read_csv('transactions.csv')
df.head()

,id,date,client_id,card_id,amount,use_chip,merchant_id,merchant_city,merchant_state,zip,mcc,errors
0,7475327,2010-01-01 00:01:00,1556,2972,$-77.00,Swipe Transaction,59935,Beulah,ND,58523.0,5499,NaN
1,7475328,2010-01-01 00:02:00,561,4575,$14.57,Swipe Transaction,67570,Bettendorf,IA,52722.0,5311,NaN
2,7475329,2010-01-01 00:02:00,1129,102,$80.00,Swipe Transaction,27092,Vista,CA,92084.0,4829,NaN
3,7475331,2010-01-01 00:05:00,430,2860,$200.00,Swipe Transaction,27092,Crown Point,IN,46307.0,4829,NaN
4,7475332,2010-01-01 00:06:00,848,3915,$46.41,Swipe Transaction,13051,Harwood,MD,20776.0,5813,NaN

In [14]:
df.tail()

,id,date,client_id,card_id,amount,use_chip,merchant_id,merchant_city,merchant_state,zip,mcc,errors
9995,7487276,2010-01-04 06:13:00,461,5482,$5.63,Swipe Transaction,78758,Canton,MI,48188.0,5411,NaN
9996,7487277,2010-01-04 06:13:00,571,5960,$2.15,Swipe Transaction,20519,Hedgesville,WV,25427.0,5942,NaN
9997,7487279,2010-01-04 06:13:00,1692,3646,$36.22,Online Transaction,39021,ONLINE,NaN,NaN,4784,NaN
9998,7487280,2010-01-04 06:14:00,161,5588,$2.11,Swipe Transaction,78454,Waco,TX,76707.0,5812,NaN
9999,7487282,2010-01-04 06:14:00,360,2611,$36.52,Swipe Transaction,31893,Atlantic City,NJ,8401.0,5311,NaN

In [9]:
df_cards = pd.read_csv('cards_data.csv')
df_cards.head()

,id,client_id,card_brand,card_type,card_number,expires,cvv,has_chip,num_cards_issued,credit_limit,acct_open_date,year_pin_last_changed,card_on_dark_web
0,4524,825,Visa,Debit,4344676511950444,12/2022,623,YES,2,$24295,09/2002,2008,No
1,2731,825,Visa,Debit,4956965974959986,12/2020,393,YES,2,$21968,04/2014,2014,No
2,3701,825,Visa,Debit,4582313478255491,02/2024,719,YES,2,$46414,07/2003,2004,No
3,42,825,Visa,Credit,4879494103069057,08/2024,693,NO,1,$12400,01/2003,2012,No
4,4659,825,Mastercard,Debit (Prepaid),5722874738736011,03/2009,75,YES,1,$28,09/2008,2009,No

In [10]:
df_users = pd.read_csv('users_data.csv')
df_users.head()

,id,current_age,retirement_age,birth_year,birth_month,gender,address,latitude,longitude,per_capita_income,yearly_income,total_debt,credit_score,num_credit_cards
0,825,53,66,1966,11,Female,462 Rose Lane,34.15,-117.76,$29278,$59696,$127613,787,5
1,1746,53,68,1966,12,Female,3606 Federal Boulevard,40.76,-73.74,$37891,$77254,$191349,701,5
2,1718,81,67,1938,11,Female,766 Third Drive,34.02,-117.89,$22681,$33483,$196,698,5
3,708,63,63,1957,1,Female,3 Madison Street,40.71,-73.99,$163145,$249925,$202328,722,4
4,1164,43,70,1976,9,Male,9620 Valley Stream Drive,37.76,-122.44,$53797,$109687,$183855,675,1

In [ ]:
df = df.drop(columns=['errors'])
df['amount'] = df['amount'].replace('[\$,]', '', regex=True).astype(float)

df_cards['credit_limit'] = df_cards['credit_limit'].replace('[\$,]','', regex=True).astype(float)

cols_to_alter = ['per_capita_income', 'yearly_income', 'total_debt']
for col in cols_to_alter:
    df_users[col] = df_users[col].replace('[\$]', '', regex=True).astype(float)

In [15]:
df.to_csv('transactions_c.csv', index=False)
df_cards.to_csv('cards_c.csv', index=False)
df_users.to_csv('users_c.csv', index=False)